version: "3"
services:

  api-gateway:
    build: "./api-gateway"
    depends_on:
      - listings-service
      - users-service
    ports:
      - 7050:7050
    volumes:
      - ./api-gateway:/opt/app

  listings-service:
    build: "./listings-service"
    depends_on:
      - listings-service-db
    environment:
      - DB_URI=mysql://root:LPr4ck3r2@listings-service-db/db?charset=UTF8
    ports:
      - 6100:6100
    volumes:
      - ./listings-service:/opt/app

  listings-service-db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 7200:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      - DB_URI=mysql://root:LPr4ck3r2@users-service-db/db?charset=UTF8
    ports:
      - 6101:6101
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 7201:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw